//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMS_BirthReport
    {
        public int patientID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string doctorName { get; set; }
        public string Status { get; set; }
    }
}
