//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMS_PatientCaseStudy
    {
        public int prescriptionID { get; set; }
        public string FoodAllergies { get; set; }
        public string TendencyBlood { get; set; }
        public string HeartDisease { get; set; }
        public string HighBloodPressure { get; set; }
        public string Diabetic { get; set; }
        public string Surgery { get; set; }
        public string Accident { get; set; }
        public string Other { get; set; }
        public string FamilyMedicalHistory { get; set; }
        public string CurrentMedication { get; set; }
        public string BreastFeeding { get; set; }
        public string HealthInsurance { get; set; }
        public string LowIncome { get; set; }
        public string Reference { get; set; }
        public string Status { get; set; }
    }
}
